// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbMunicipios = new HashSet<tbMunicipios>();
            tbPersonas = new HashSet<tbPersonas>();
            tbSucursales = new HashSet<tbSucursales>();
        }

        public int depto_Id { get; set; }
        public string depto_Codigo { get; set; }
        public string depto_Descripcion { get; set; }
        public bool? depto_EsEliminado { get; set; }

        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
        public virtual ICollection<tbSucursales> tbSucursales { get; set; }
    }
}