// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class tbEmpleadoSucursales
    {
        public tbEmpleadoSucursales()
        {
            tbViajeEmpleadoSucursales = new HashSet<tbViajeEmpleadoSucursales>();
        }

        public int empSuc_Id { get; set; }
        public int? emp_Id { get; set; }
        public int? suc_Id { get; set; }
        public double? distanciaKilometros { get; set; }

        public virtual tbEmpleados emp { get; set; }
        public virtual tbSucursales suc { get; set; }
        public virtual ICollection<tbViajeEmpleadoSucursales> tbViajeEmpleadoSucursales { get; set; }
    }
}