// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class tbModulos
    {
        public tbModulos()
        {
            tbPantallas = new HashSet<tbPantallas>();
        }

        public int mod_Id { get; set; }
        public int comp_Id { get; set; }
        public string mod_Descripcion { get; set; }

        public virtual tbComponentes comp { get; set; }
        public virtual ICollection<tbPantallas> tbPantallas { get; set; }
    }
}