// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbPersonas = new HashSet<tbPersonas>();
            tbSucursales = new HashSet<tbSucursales>();
        }

        public int mpio_Id { get; set; }
        public string mpio_Codigo { get; set; }
        public string mpio_Descripcion { get; set; }
        public int depto_Id { get; set; }
        public bool? mpio_EsEliminado { get; set; }

        public virtual tbDepartamentos depto { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
        public virtual ICollection<tbSucursales> tbSucursales { get; set; }
    }
}