// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class tbPantallas
    {
        public tbPantallas()
        {
            tbRolPantallas = new HashSet<tbRolPantallas>();
        }

        public int pant_Id { get; set; }
        public int mod_Id { get; set; }
        public string pant_Descripcion { get; set; }

        public virtual tbModulos mod { get; set; }
        public virtual ICollection<tbRolPantallas> tbRolPantallas { get; set; }
    }
}