// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class tbPersonas
    {
        public tbPersonas()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
            tbTransportistas = new HashSet<tbTransportistas>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int per_Id { get; set; }
        public string per_Identidad { get; set; }
        public string per_PrimerNombre { get; set; }
        public string per_SegundoNombre { get; set; }
        public string per_PrimerApellido { get; set; }
        public string per_SegundoApellido { get; set; }
        public DateTime per_FechaNac { get; set; }
        public string per_Sexo { get; set; }
        public string per_Correo { get; set; }
        public string per_Telefono { get; set; }
        public string per_Direccion { get; set; }
        public int depto_Id { get; set; }
        public int mpio_Id { get; set; }
        public bool? per_EsEliminado { get; set; }
        public string per_Esciv { get; set; }

        public virtual tbDepartamentos depto { get; set; }
        public virtual tbMunicipios mpio { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbTransportistas> tbTransportistas { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}