// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class tbSucursales
    {
        public tbSucursales()
        {
            tbEmpleadoSucursales = new HashSet<tbEmpleadoSucursales>();
        }

        public int suc_Id { get; set; }
        public string suc_Nombre { get; set; }
        public string suc_Direccion { get; set; }
        public string suc_Telefono { get; set; }
        public string suc_Correo { get; set; }
        public int depto_Id { get; set; }
        public int mpio_Id { get; set; }
        public bool? suc_Estado { get; set; }
        public bool? suc_EsEliminado { get; set; }

        public virtual tbDepartamentos depto { get; set; }
        public virtual tbMunicipios mpio { get; set; }
        public virtual ICollection<tbEmpleadoSucursales> tbEmpleadoSucursales { get; set; }
    }
}