// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class tbUsuarios
    {
        public int usu_Id { get; set; }
        public string usu_NombreUsuario { get; set; }
        public byte[] usu_Contraseña { get; set; }
        public bool? usu_Estado { get; set; }
        public bool usu_EsEliminado { get; set; }
        public int per_Id { get; set; }
        public string usu_ImagenPerfil { get; set; }
        public bool? usu_Logueado { get; set; }
        public int rol_Id { get; set; }

        public virtual tbPersonas per { get; set; }
        public virtual tbRoles rol { get; set; }
    }
}