// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class tbViajes
    {
        public tbViajes()
        {
            tbViajeEmpleadoSucursales = new HashSet<tbViajeEmpleadoSucursales>();
        }

        public int via_Id { get; set; }
        public int trans_Id { get; set; }
        public DateTime? via_FechaSalida { get; set; }
        public double? via_KMTotalRecorridos { get; set; }

        public virtual tbTransportistas trans { get; set; }
        public virtual ICollection<tbViajeEmpleadoSucursales> tbViajeEmpleadoSucursales { get; set; }
    }
}