// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class tbViajeEmpleadoSucursales
    {
        public int viaEmpSuc_Id { get; set; }
        public int? via_Id { get; set; }
        public int? empSuc_Id { get; set; }

        public virtual tbEmpleadoSucursales empSuc { get; set; }
        public virtual tbViajes via { get; set; }
    }
}